Fix/limit order pivot
mangrovedao/mangrove.js pull request #1436
Opened 2023-07-13 15:37 UTC by jkrivine

2023-07-13 16:37 UTC, peterMangrove commented on src/util/trade.ts
> +      /* (maker) wants is takerWants*/ inbound_tkn.fromUnits(gives)
Okay, but it says "takerWants" in both line. That seems wrong

2023-07-14 06:59 UTC, peterMangrove requested changes

2023-07-14 06:59 UTC, peterMangrove commented on CHANGELOG.md
> +# 1.4.10
The release workflow will add this. Remove this line

2023-07-14 07:15 UTC, jkrivine commented on CHANGELOG.md
> +# 1.4.10
even if I publish with the UI ?

2023-07-14 07:29 UTC, peterMangrove commented on CHANGELOG.md
> +# 1.4.10
I'm not entirely sure what you mean by UI. If you mean running the workflow using the UI, then yes. I'm 100% sure, but i think it will bump it to 1.14.11 in the changelog. We can try, and see what happens

2023-07-14 07:29 UTC, peterMangrove approved these changes

2023-07-14 08:46 UTC, merged