chore(conversion): Use tickPriceHelper when available for outbound/inbound raw conversions
mangrovedao/mangrove.js pull request #1675
Opened 2023-12-12 11:18 UTC by lnist

2023-12-12 12:08 UTC, dontrolle requested changes
Partial review of first changeset.

2023-12-12 12:08 UTC, dontrolle commented on src/util/tickPriceHelper.ts
> +  outbound: TokenCalculations;
These four fields should really be `readonly`, right? 

The need becomes more pronounced when we start caching fields calculated from other fields.

2023-12-12 12:08 UTC, dontrolle commented on src/util/tickPriceHelper.ts
> +    this.outbound = this.ba === "bids" ? this.market.quote : this.market.base;
One could also calculating inbound and outbound each time they're needed below. I think it's ok to cache them - but probably a good idea to add readonly'ness of the fields.

2023-12-12 12:28 UTC, dontrolle commented on src/util/tickPriceHelper.ts
> +    this.outbound = this.ba === "bids" ? this.market.quote : this.market.base;
Update: With revised changeset - see however comment on Semibook that it looks weird to get inbound/outbound from TickPriceHelper - and it may, e.g., make more sense to cache inbound/outbound token on Semibook (if any caching is to be done).

2023-12-12 12:37 UTC, dontrolle commented on src/kandel/coreKandelInstance.ts
> +          gives: this.distributionHelper.bidTickPriceHelper.rawOutbound(
I understand that we've added some functionality concerning price conversions to `TickPriceHelper`, But I'm wondering whether we're taking it a bit too far here. 

We've also decided to collect some functionality concerning conversion of "raw" values to "non-raw" values on `Token` (and `TokenCalculation`). I'm not sure adding the wrapper function and using it like here on `TickPriceHelper` actually improves readability? 

At the least I need a bit of convincing.

2023-12-12 12:38 UTC, dontrolle commented on src/kandel/coreKandelInstance.ts
> +          gives: this.distributionHelper.bidTickPriceHelper.rawOutbound(
In addition - might we consider improving the naming of the `toUnits` function, instead? Say to `toRawUnits` - or something like that?

2023-12-12 12:39 UTC, dontrolle commented on src/util/tickPriceHelper.ts
> +  /** Converts outbound token amount from public amount to internal contract amount.  */
See comments for `src/kandel/coreKandelInstance.ts`

2023-12-13 10:23 UTC, lnist commented
Closing in favor of doing a well-designed overhaul later.

2023-12-13 10:23 UTC, closed without merging